default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: TeachersTimeTracker_development

test:
  <<: *default
  database: TeachersTimeTracker_test

production:
  <<: *default
  database: TeachersTimeTracker_production
  username: postgres
  password: <%= ENV['TIMETRACKER_DATABASE_PASSWORD'] %>
